//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OpenKNX.Toolbox.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("OpenKNX.Toolbox.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add.
        /// </summary>
        public static string Add {
            get {
                return ResourceManager.GetString("Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address: 1.1.4.
        /// </summary>
        public static string AddressPlaceholder {
            get {
                return ResourceManager.GetString("AddressPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The application with ID {0} is not present in the local database..
        /// </summary>
        public static string ApplicationIdMissing {
            get {
                return ResourceManager.GetString("ApplicationIdMissing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The application version {0} is not present in the local database..
        /// </summary>
        public static string ApplicationVersionMissing {
            get {
                return ResourceManager.GetString("ApplicationVersionMissing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string ConnectionName {
            get {
                return ResourceManager.GetString("ConnectionName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connections.
        /// </summary>
        public static string Connections {
            get {
                return ResourceManager.GetString("Connections", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The application version contains no ContentModel..
        /// </summary>
        public static string ContentModelMissing {
            get {
                return ResourceManager.GetString("ContentModelMissing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create knxprod.
        /// </summary>
        public static string CreateKnxprod {
            get {
                return ResourceManager.GetString("CreateKnxprod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create knxprod {0}.
        /// </summary>
        public static string CreateKnxprodDisplay {
            get {
                return ResourceManager.GetString("CreateKnxprodDisplay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current Action.
        /// </summary>
        public static string CurrentAction {
            get {
                return ResourceManager.GetString("CurrentAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete file.
        /// </summary>
        public static string DeleteFile {
            get {
                return ResourceManager.GetString("DeleteFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete file {0}.
        /// </summary>
        public static string DeleteFileDisplay {
            get {
                return ResourceManager.GetString("DeleteFileDisplay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error deleting the firmware directory:.
        /// </summary>
        public static string DeleteFirmwareDirError {
            get {
                return ResourceManager.GetString("DeleteFirmwareDirError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Details.
        /// </summary>
        public static string Details {
            get {
                return ResourceManager.GetString("Details", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OpenKNX IP devices are shown here.
        /// </summary>
        public static string DeviceListIntro {
            get {
                return ResourceManager.GetString("DeviceListIntro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Device Manager.
        /// </summary>
        public static string DeviceManager {
            get {
                return ResourceManager.GetString("DeviceManager", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Display language.
        /// </summary>
        public static string DisplayLanguage {
            get {
                return ResourceManager.GetString("DisplayLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download.
        /// </summary>
        public static string Download {
            get {
                return ResourceManager.GetString("Download", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download file.
        /// </summary>
        public static string DownloadFile {
            get {
                return ResourceManager.GetString("DownloadFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download release.
        /// </summary>
        public static string DownloadRelease {
            get {
                return ResourceManager.GetString("DownloadRelease", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Drop file here to upload.
        /// </summary>
        public static string DropFileUpload {
            get {
                return ResourceManager.GetString("DropFileUpload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        public static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File Manager.
        /// </summary>
        public static string FileManager {
            get {
                return ResourceManager.GetString("FileManager", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Firmware Manager.
        /// </summary>
        public static string FirmwareManager {
            get {
                return ResourceManager.GetString("FirmwareManager", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Flash release.
        /// </summary>
        public static string FlashRelease {
            get {
                return ResourceManager.GetString("FlashRelease", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Flash to device.
        /// </summary>
        public static string FlashToDevice {
            get {
                return ResourceManager.GetString("FlashToDevice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gateway selection.
        /// </summary>
        public static string GatewaySelection {
            get {
                return ResourceManager.GetString("GatewaySelection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to History.
        /// </summary>
        public static string History {
            get {
                return ResourceManager.GetString("History", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The specified address is invalid..
        /// </summary>
        public static string InvalidAddress {
            get {
                return ResourceManager.GetString("InvalidAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IP address.
        /// </summary>
        public static string IpAddress {
            get {
                return ResourceManager.GetString("IpAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IP port.
        /// </summary>
        public static string IpPort {
            get {
                return ResourceManager.GetString("IpPort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is TCP.
        /// </summary>
        public static string IsTcp {
            get {
                return ResourceManager.GetString("IsTcp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language.
        /// </summary>
        public static string Language {
            get {
                return ResourceManager.GetString("Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Multiple products were found..
        /// </summary>
        public static string MultipleProductsFound {
            get {
                return ResourceManager.GetString("MultipleProductsFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add new connection.
        /// </summary>
        public static string NewConnectionTitle {
            get {
                return ResourceManager.GetString("NewConnectionTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No connection to a gateway was established..
        /// </summary>
        public static string NoGatewayConnection {
            get {
                return ResourceManager.GetString("NoGatewayConnection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No matching products were found..
        /// </summary>
        public static string NoMatchingProducts {
            get {
                return ResourceManager.GetString("NoMatchingProducts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No product was selected..
        /// </summary>
        public static string NoProductSelected {
            get {
                return ResourceManager.GetString("NoProductSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No update version is selected..
        /// </summary>
        public static string NoUpdateVersionSelected {
            get {
                return ResourceManager.GetString("NoUpdateVersionSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open thread on knx-user-forum.de.
        /// </summary>
        public static string OpenHelpThread {
            get {
                return ResourceManager.GetString("OpenHelpThread", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open release notes.
        /// </summary>
        public static string OpenReleaseNotes {
            get {
                return ResourceManager.GetString("OpenReleaseNotes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open repository on GitHub.
        /// </summary>
        public static string OpenRepository {
            get {
                return ResourceManager.GetString("OpenRepository", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open website.
        /// </summary>
        public static string OpenWebsite {
            get {
                return ResourceManager.GetString("OpenWebsite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pending Actions.
        /// </summary>
        public static string PendingActions {
            get {
                return ResourceManager.GetString("PendingActions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Refresh.
        /// </summary>
        public static string Refresh {
            get {
                return ResourceManager.GetString("Refresh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Release is not available locally..
        /// </summary>
        public static string ReleaseNotLocal {
            get {
                return ResourceManager.GetString("ReleaseNotLocal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reload.
        /// </summary>
        public static string Reload {
            get {
                return ResourceManager.GetString("Reload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reload list.
        /// </summary>
        public static string ReloadList {
            get {
                return ResourceManager.GetString("ReloadList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restart required for language change.
        /// </summary>
        public static string RestartRequired {
            get {
                return ResourceManager.GetString("RestartRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scheduled Actions.
        /// </summary>
        public static string ScheduledActions {
            get {
                return ResourceManager.GetString("ScheduledActions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select.
        /// </summary>
        public static string Select {
            get {
                return ResourceManager.GetString("Select", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selected Device.
        /// </summary>
        public static string SelectedDevice {
            get {
                return ResourceManager.GetString("SelectedDevice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The selected item is not a file..
        /// </summary>
        public static string SelectedItemNotFile {
            get {
                return ResourceManager.GetString("SelectedItemNotFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select device to flash.
        /// </summary>
        public static string SelectFlashDevice {
            get {
                return ResourceManager.GetString("SelectFlashDevice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string Settings {
            get {
                return ResourceManager.GetString("Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown action.
        /// </summary>
        public static string UnknownAction {
            get {
                return ResourceManager.GetString("UnknownAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown action type: .
        /// </summary>
        public static string UnknownActionType {
            get {
                return ResourceManager.GetString("UnknownActionType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown port.
        /// </summary>
        public static string UnknownPort {
            get {
                return ResourceManager.GetString("UnknownPort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A device reported an unknown port: .
        /// </summary>
        public static string UnknownPortMessage {
            get {
                return ResourceManager.GetString("UnknownPortMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown.
        /// </summary>
        public static string UnknownVersion {
            get {
                return ResourceManager.GetString("UnknownVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update available!.
        /// </summary>
        public static string UpdateAvailable {
            get {
                return ResourceManager.GetString("UpdateAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update not possible.
        /// </summary>
        public static string UpdateNotPossible {
            get {
                return ResourceManager.GetString("UpdateNotPossible", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upload file.
        /// </summary>
        public static string UploadFile {
            get {
                return ResourceManager.GetString("UploadFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The application version is not available locally yet and will be downloaded now..
        /// </summary>
        public static string VersionNotLocalYet {
            get {
                return ResourceManager.GetString("VersionNotLocalYet", resourceCulture);
            }
        }
    }
}
