name: .NET Core Desktop

permissions:
  contents: write

on:
  workflow_dispatch:        # Manuell starten
  push:
    branches:
      - '**'

jobs:
  build:
    if: github.event_name == 'workflow_dispatch' ||
      contains(github.event.head_commit.message, '[publish]')
    runs-on: windows-latest  # For a list of available runner types, refer to
           
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        submodules: true
        fetch-depth: 0

    # Install the .NET Core workload
    - name: Install .NET Core
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 10.0.x

    - name: Restore
      run: dotnet restore ./OpenKNX.Toolbox/OpenKNX.Toolbox.csproj
      
    - name: Build
      run: dotnet build ./OpenKNX.Toolbox/OpenKNX.Toolbox.csproj -c Release
    
    - name: Publish
      run: dotnet publish ./OpenKNX.Toolbox/OpenKNX.Toolbox.csproj -c Release -r win-x86 -o ./publish -p:PublishSingleFile=true --self-contained
    
    - name: Read version from EXE
      id: version
      shell: pwsh
      run: |
          $exePath = "./publish/OpenKNX.Toolbox.exe"
          if (-not (Test-Path $exePath)) {
              throw "$exePath konnte nicht gefunden werden"
          }

          $info = (Get-Item $exePath).VersionInfo
          $version = $info.FileVersion

          if (-not $version) { throw "Konnte ProductVersion nicht auslesen." }
          

          $branch = "${{ github.ref_name }}"
          # Branch normalisieren (feature/test → feature-test)
          $safeBranch = $branch -replace '[^a-zA-Z0-9\-]', '_'
      
          if ($branch -eq "main") {
              $version = "v$version"
          } else {
              $version = "v$version-$safeBranch"
          }
          echo "Gefundene Version: $version"
          echo "version=$version" >> $env:GITHUB_OUTPUT

    - name: Create ZIP
      run: |
          Get-ChildItem -Path "./publish" -Filter "*.pdb" -Recurse | Remove-Item -Force
          powershell Compress-Archive -Path ./publish/* -DestinationPath ./OpenKNX.Toolbox.Binaries.zip -Force

    - name: Create Git tag
      shell: pwsh
      run: |
          git tag ${{ steps.version.outputs.version }}
          git push origin ${{ steps.version.outputs.version }}
          
    - name: Create GitHub Release
      uses: softprops/action-gh-release@v2
      with:
        tag_name: ${{ steps.version.outputs.version }}
        name: ${{ steps.version.outputs.version }}
        files: OpenKNX.Toolbox.Binaries.zip
        prerelease: ${{ github.ref_name != 'main' }}
