name: .NET Core Desktop

on:
  workflow_dispatch:        # Manuell starten
  push:
    branches:
      - main

jobs:
  build:
    if: github.event_name == 'workflow_dispatch' ||
      contains(github.event.head_commit.message, '[publish]')
    runs-on: windows-latest  # For a list of available runner types, refer to
           
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    # Install the .NET Core workload
    - name: Install .NET Core
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 10.0.x

    - name: Restore
      run: dotnet restore ./OpenKNX.Toolbox/OpenKNX.Toolbox.csproj
      
    - name: Build
      run: dotnet build ./OpenKNX.Toolbox/OpenKNX.Toolbox.csproj -c Release
    
    - name: Publish
      run: dotnet publish ./OpenKNX.Toolbox/OpenKNX.Toolbox.csproj -c Release -r win-x86 -o ./publish -p:PublishSingleFile=true --self-contained
    
    - name: Read version from EXE
      id: version
      shell: pwsh
      run: |
          $exe = Get-ChildItem -Path "./publish" -Filter "*.exe" | Select-Object -First 1
          if (-not $exe) { throw "Keine EXE im publish-Ordner gefunden." }

          $info = (Get-Item $exe.FullName).VersionInfo
          $version = $info.ProductVersion

          if (-not $version) { throw "Konnte ProductVersion nicht auslesen." }

          echo "Gefundene Version: $version"
          echo "version=$version" >> $env:GITHUB_OUTPUT

    - name: Create ZIP
      run: |
          powershell Compress-Archive -Path ./publish/* -DestinationPath ./OpenKNX.Toolbox_${{ steps.version.outputs.version }}.zip -Force

    - name: Create Git tag
      run: |
          git tag v${{ steps.version.outputs.version }}
          git push origin v${{ steps.version.outputs.version }}

    - name: Create GitHub Release
      uses: softprops/action-gh-release@v2
      with:
        tag_name: v${{ steps.version.outputs.version }}
        name: v${{ steps.version.outputs.version }}
        files: OpenKNX.Toolbox_${{ steps.version.outputs.version }}.zip
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
